services:
  rancher-server:
    image: rancher/rancher:latest
    container_name: rancher-server
    restart: unless-stopped
    privileged: true
    environment:
      CATTLE_BOOTSTRAP_PASSWORD: ${CATTLE_BOOTSTRAP_PASSWORD:-10mTsybsmfJVnZhH}
    volumes:
      - ./data/rancher:/var/lib/rancher
    ports:
      - "80:80"
      - "443:443"
