services:
  rancher-server:
    image: rancher/rancher:latest
    container_name: rancher-server
    restart: unless-stopped
    privileged: true
    environment:
      CATTLE_BOOTSTRAP_PASSWORD: ${CATTLE_BOOTSTRAP_PASSWORD:-10mTsybsmfJVnZhH}
    volumes:
      - ./data/rancher:/var/lib/rancher:Z
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - "80:80"
      - "443:443"
    tmpfs:
      - /run:rw,noexec,nosuid,size=100m
      - /var/run:rw,noexec,nosuid,size=100m
      - /tmp:rw,noexec,nosuid,size=100m
    security_opt:
      - seccomp:unconfined
      - label:disable
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_PTRACE
      - DAC_READ_SEARCH
