services:
  postgres:
    image: postgres:latest
    container_name: jira-postgres
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jirapassword
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: always
  jira:
    image: atlassian/jira-software:latest
    container_name: jira
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jira
      ATL_JDBC_USER: jira
      ATL_JDBC_PASSWORD: jirapassword
      ATL_DB_TYPE: postgres
    volumes:
      - ./data/jira-data:/var/atlassian/application-data/jira
    restart: always
