services:
  confluence:
    image: haxqer/confluence:8.5.14
    container_name: confluence
    environment:
      - TZ=${TZ}
      - JVM_MINIMUM_MEMORY=4g
      - JVM_MAXIMUM_MEMORY=4g
      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    depends_on:
      - pgsql
    ports:
      - "8090:8090"
    volumes:
      - ./data/confluence:/var/confluence
      - ./server.xml:/opt/confluence/conf/server.xml
    restart: always
    networks:
      - confluence_net
  pgsql:
    image: postgres:15
    container_name: pgsql
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    restart: always
    networks:
      - confluence_net
      # nginx:
      #   image: nginx:1.25
      #   container_name: confluence_nginx
      #   ports:
      #     - "80:80"
      #     - "443:443"
      #   volumes:
      #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      #     - ./ssl/${SSL_CERTIFICATE}:/etc/nginx/ssl/${SSL_CERTIFICATE}:ro
      #     - ./ssl/${SSL_CERTIFICATE_KEY}:/etc/nginx/ssl/${SSL_CERTIFICATE_KEY}:ro
      #   environment:
      #     - CONFLUENCE_DOMAIN=${CONFLUENCE_DOMAIN}
      #   depends_on:
      #     - confluence
      #   restart: always
      #   networks:
      #     - confluence_net
networks:
  confluence_net:
    driver: bridge
