services:
  nginx:
    container_name: gitea-nginx
    image: nginx:${NGINX_VERSION:-1.25-alpine}
    restart: unless-stopped
    depends_on:
      gitea:
        condition: service_healthy
      drone:
        condition: service_healthy
    environment:
      - GITEA_DOMAIN=${GITEA_DOMAIN}
      - DRONE_DOMAIN=${DRONE_DOMAIN}
      - GITEA_CERT_NAME=${GITEA_CERT_NAME}
      - DRONE_CERT_NAME=${DRONE_CERT_NAME}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - cicd_net
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/conf.d:/etc/nginx/templates:ro
      - ./data/nginx/logs:/var/log/nginx
      - ./data/nginx/cache:/var/cache/nginx
      - ./data/ssl:/etc/nginx/ssl:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "-H", "Host: gitea.devops.io", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
  gitea:
    container_name: gitea
    image: gitea/gitea:${GITEA_VERSION:-1.21.5}
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - APP_NAME="Gitea"
      - USER_UID=1000
      - USER_GID=1000
      - RUN_MODE=prod
      - PROTOCOL=https
      - DOMAIN=${GITEA_DOMAIN:-${IP_ADDRESS}}
      - SSH_DOMAIN=${GITEA_DOMAIN:-${IP_ADDRESS}}
      - HTTP_PORT=3000
      - ROOT_URL=https://${GITEA_DOMAIN:-${IP_ADDRESS}}
      - SSH_PORT=2222
      - SSH_LISTEN_PORT=22
      - DB_TYPE=sqlite3
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      - GITEA__server__DOMAIN=${GITEA_DOMAIN:-${IP_ADDRESS}}
      - GITEA__server__SSH_DOMAIN=${GITEA_DOMAIN:-${IP_ADDRESS}}
      - GITEA__server__ROOT_URL=https://${GITEA_DOMAIN:-${IP_ADDRESS}}
      - GITEA__security__INSTALL_LOCK=true
    ports:
      - "3000:3000" # 直接访问端口
      - "2222:22" # SSH 端口
    networks:
      - cicd_net
    volumes:
      - ./data/gitea:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  drone:
    container_name: drone
    image: drone/drone:${DRONE_VERSION:-2.23.0}
    restart: unless-stopped
    depends_on:
      gitea:
        condition: service_healthy
    environment:
      # https://docs.drone.io/server/provider/gitea/
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_DATABASE_DATASOURCE=/data/database.sqlite
      - DRONE_GITEA_SERVER=https://${GITEA_DOMAIN:-${IP_ADDRESS}}/
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_PROTO=https
      - DRONE_SERVER_HOST=${DRONE_DOMAIN:-${IP_ADDRESS}:3001}
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TRACE=false
      - DRONE_CLEANUP_INTERVAL=24h
      - DRONE_CLEANUP_DISABLED=false
    ports:
      - "3001:80" # 直接访问端口
      - "9000:9000" # 内部 RPC 端口
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/drone:/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
  drone-runner:
    container_name: drone-runner
    image: drone/drone-runner-docker:${DRONE_RUNNER_VERSION:-1.8.3}
    restart: unless-stopped
    depends_on:
      drone:
        condition: service_healthy
    environment:
      # https://docs.drone.io/runner/docker/installation/linux/
      # https://docs.drone.io/server/metrics/
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone:80
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_NAME="drone-runner"
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NETWORKS=cicd_net
      - DRONE_DEBUG=false
      - DRONE_TRACE=false
      - DRONE_RUNNER_ENVIRON=PLUGIN_PRIVILEGED:true
      - DRONE_UI_USERNAME=${GITEA_ADMIN_USER:-root}
      - DRONE_UI_PASSWORD=${DRONE_RPC_SECRET}
    ports:
      - "3002:3000" # Runner UI 端口
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
networks:
  cicd_net:
    name: cicd_net
