name: Ruby Test
on:
  push:
    branches: [main]
env:
  RUBY_VERSION: '3.2.0'
jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.2 # 直接使用官方 Ruby 镜像
    steps:
      - name: Install Node
        run: |
          apt update
          apt install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt install -y nodejs
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          bundle install
      - name: Execute t.rb
        run: ruby t.rb
    # - name: Notify Lark
    #   run: |
    #     curl -X POST "$LARK_WEBHOOK" \
    #       -H "Content-Type: application/json" \
    #       -d '{"msg_type":"text","content":{"text":"CI 执行完成"}}'
    #   env:
    #     LARK_WEBHOOK: ${{ secrets.LARK_WEBHOOK }}
