version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea@passwd
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ./data/gitea:/data
    restart: always
    depends_on:
      - postgres
    networks:
      - gitea_net
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea@passwd
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - gitea_net
networks:
  gitea_net:
    name: gitea_net
