version: '3'
services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=postgres:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - /data/volumes/gitea:/data
    restart: always
    networks:
      - gitea
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: gitea
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
    volumes:
      - /data/volumes/postgresql:/var/lib/postgresql/data
    restart: always
    networks:
      - gitea

networks:
  gitea:
    external: false