global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: 
      - alertmanager:9093
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'node'
  static_configs:
  - targets: 
    - node-exporter:9100

- job_name: 'devops-tcp'
  metrics_path: /probe
  params:
    module: [tcp_connect]
  static_configs:
  - targets:
      - google.com:443
      - baidu.com:443
    labels:
      module: tcp
      env: prod
      project: devops
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: blackbox-exporter:9115
