version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11.13-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=1qaz2wsx
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    networks:
      - rabbitmq
networks:
  rabbitmq:
    name: rabbitmq
