services:
  redis:
    restart: always
    image: redis:latest
    command:
      - --loglevel warning
    volumes:
      - ./data/redis:/data:Z

  postgresql:
    restart: always
    image: postgresql:latest
    volumes:
      - ./data/postgresql:/var/lib/postgresql:Z
    environment:
      - DB_USER=gitlab
      - DB_PASS=password
      - DB_NAME=gitlabhq_production
      - DB_EXTENSION=pg_trgm,btree_gist

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab"
    ports:
      - "8000:80"
      - "8443:443"
      - "2222:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/log:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      TZ: "Asia/Shanghai"
      GITLAB_OMNIBUS_CONFIG: |-
        external_url 'https://gitlab.devops.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        DEBUG = false
        DB_ADAPTER = postgresql
        DB_HOST = postgresql
        DB_PORT = 5432
        DB_USER = gitlab
        DB_PASS = password
        DB_NAME = gitlabhq_production
        REDIS_HOST = redis
        REDIS_PORT = 6379
    depends_on:
      - redis
      - postgresql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/gitlab.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - gitlab

