version: '3'
services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    ports:
      - '80:80'
      - '2222:22'
    volumes:
      - ./config/gitlab:/etc/gitlab
      - ./log/gitlab:/var/log/gitlab
      - ./data/gitlab:/var/opt/gitlab
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |-
        external_url 'http://gitlab.devops.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    networks:
      - gitlab
networks:
  gitlab:
    name: gitlab
