version: "3"
services:
  apisix:
    image: apache/apisix:latest
    restart: always
    volumes:
      - ./logs/apisix:/usr/local/apisix/logs
      - ./config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - 9180:9180
      - 9080:9080
      - 9443:9443
    networks:
      - apisix
  etcd:
    image: bitnami/etcd:latest
    restart: always
    volumes:
      - ./data/etcd:/opt/bitnami/etcd/data
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
    ports:
      - 2379:2379
    networks:
      - apisix
networks:
  apisix:
    name: apisix
