services:
  nacos:
    image: nacos/nacos-server:v2.5.1
    container_name: nacos-server
    env_file:
      - .env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./data/logs:/home/nacos/logs
      - ./data/data:/home/nacos/data
    restart: unless-stopped
