services:
  nacos:
    image: nacos/nacos-server:v3.2.4
    container_name: nacos-server
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./data/logs:/home/nacos/logs
      - ./data/data:/home/nacos/data
    restart: unless-stopped
