version: '3.8'
services:
  gitness:
    image: harness/gitness
    container_name: gitness
    environment:
      - GITNESS_URL_BASE=http://localhost:3000
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/gitness-data:/data
    restart: always
