services:
  confluence:
    image: haxqer/jira:9.17.2
    container_name: jira
    environment:
      - TZ=Asia/Shanghai
      # - JVM_MINIMUM_MEMORY=4g
      # - JVM_MAXIMUM_MEMORY=4g
      # - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=4g'
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    volumes:
      - ./data/jira:/var/jira
      # - ./server.xml:/opt/confluence/conf/server.xml
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=jira
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=123456
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_bin",
        "--transaction-isolation=READ-COMMITTED",
        "--innodb_log_file_size=256M",
        "--max_allowed_packet=256M",
        "--log_bin_trust_function_creators=1",
      ]
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
