services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijs@passwd
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  wiki:
    image: requarks/wiki:2
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijs@passwd
      DB_NAME: wiki
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - wiki
networks:
  wiki:
    name: wiki
