version: '3'
services:
  influxdb:
    image: "influxdb:latest"
    # hostname: "monitoring_influxdb"
    # container_name: monitoring_influxdb
    ports: 
      - "8086:8086"
    volumes:
      - "influx-data:/var/lib/influxdb"
    networks:
      - tick-network
  chronograf:
    image: "chronograf:latest"
    # hostname: "monitoring_chronograf"
    # container_name: monitoring_chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports: 
      - "8888:8888"
    volumes: 
      - "chronograf-data:/var/lib/chronograf"
    links:
      - influxdb
      - kapacitor
    networks:
      - tick-network
  telegraf:
    image: "telegraf:latest"
    # hostname: "monitoring_telegraf"
    # container_name: monitoring_telegraf
    volumes:
      - "telegraf-data:/etc/telegraf/"
    links:
      - influxdb
    networks:
      - tick-network
  kapacitor:
    image: "kapacitor:latest"
    hostname: "monitoring_kapacitor"
    container_name: "monitoring_kapacitor"
    volumes: 
      - "kapacitor-data:/var/lib/kapacitor"
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
    networks:
      - tick-network

volumes:
  telegraf-data:
  chronograf-data:
  influx-data:
  kapacitor-data:

networks:
  tick-network: