version: "3"

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: "minio_admin"
      MINIO_ROOT_PASSWORD: "minio_passwd"
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  minio:
    name: minio
