# ignored options for 'wg-easy'
# --detach
name: wg
services:
  wg-easy:
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=172.16.1.110
      - PASSWORD_HASH=$$2a$$12$$NiVGss0jKYvezAzJ8sY21.gyu6JN7rGJMYDCVQCL27TBDYbd/8tYK
      - PORT=51821
      - WG_PORT=51820
      - ENABLE_PROMETHEUS_METRICS=true
      - UI_TRAFFIC_STATS=true
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped
    image: ghcr.io/wg-easy/wg-easy
