services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    privileged: true
    command: /usr/local/bin/redis-server --appendonly yes
    volumes:
      # - ./config/redis/redis.conf:/etc/redis/redis.conf
      - ./data/redis:/data
    networks:
      - redis
networks:
  redis:
    name: redis
