version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    privileged: true
    command: redis-server /etc/redis/redis.conf --appendonly yes
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - redis

networks:
  redis:
    name: redis